### ISSUE TITLE
setup.py?

### ISSUE THREAD

**Issue by ericmjl** [tirthajyoti/UCI-ML-API#1]
Great work putting this out there! :smile: It takes courage to release your project as open source.

I'm wondering if you'd like some guidance with making this an installable setup package, complete with a command-line executable, which can be deployed to PyPI and conda? Doing so would make this package accessible through idiomatic channels, rather than through github.

**Comment by tirthajyoti** [comment]
Hi @ericmjl , I know that would be awesome for general users and I do have experience in releasing package in PyPI channel. I have released a random database table generator on PyPI few months back.

For this particular work, I am simply limited by bandwidth to create a setup.py file and uploading it to PyPI repo. If somebody helps me with that and collaborate, I guess I can do such...

Also, for an installable package, I would not prefer the open function and user API type interface. I would rather prefer classes and methods so that a Python user can create her/his own UCI-ML object and probe the repo through that. For that, I have to transform all the internal functions into classes.
